spring.application.name: api-gateway

logging.level.io.github.resilience4j: DEBUG
logging.level.io.eventuate.examples: INFO
logging.level.org.springframework.web: DEBUG

spring.sleuth.enabled: true
spring.sleuth.sampler.probability: 1
spring.zipkin.base.url: http://${DOCKER_HOST_IP:localhost}:9411/


apigateway.timeout.millis: 1000

customer:
  destinations:
    customerServiceUrl: http://${DOCKER_HOST_IP:localhost}:8082
order:
  destinations:
    orderServiceUrl: http://${DOCKER_HOST_IP:localhost}:8081

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 1
      waitDurationInOpenState: 10000
      failureRateThreshold: 60

spring:
  cloud:
    gateway:
      routes:
        - id: create_customer
          uri: ${customer.destinations.customerServiceUrl}
          predicates:
            - Method=POST
            - Path=/customers
          filters:
            - CircuitBreaker=myCircuitBreaker
        - id: get_customers
          uri: ${customer.destinations.customerServiceUrl}
          predicates:
            - Method=get
            - Path=/customers
          filters:
            - CircuitBreaker=myCircuitBreaker
        - id: get_customer
          uri: ${customer.destinations.customerServiceUrl}
          predicates:
            - Method=get
            - Path=/customers
          filters:
            - CircuitBreaker=myCircuitBreaker
        - id: create_order
          uri: ${order.destinations.orderServiceUrl}
          predicates:
            - Method=POST
            - Path=/orders
          filters:
            - CircuitBreaker=myCircuitBreaker
        - id: get_order
          uri: ${order.destinations.orderServiceUrl}
          predicates:
            - Method=get
            - Path=/orders/{orderId}
          filters:
            - CircuitBreaker=myCircuitBreaker
        - id: get_orders
          uri: ${order.destinations.orderServiceUrl}
          predicates:
            - Method=get
            - Path=/orders
          filters:
            - CircuitBreaker=myCircuitBreaker
  web:
    resources:
      static-locations: classpath:/static,classpath:/META-INF/static-content
